[default]
default_log_level="INFO"
default_access_log="True"

request_ssl_verify="True"
request_default_user_agent="neuromorphic-checkpoint-two"

thingspeak_api_url="https://api.thingspeak.com"

[test]

[qa]

[prod]
default_access_log="False"
