"""empty message

Revision ID: 176917027ec8
Revises: 
Create Date: 2023-04-11 14:57:06.246020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176917027ec8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('moisture', sa.Float(), nullable=True),
    sa.Column('atmospheric_station', sa.Float(), nullable=True),
    sa.Column('atmospheric_sea', sa.Float(), nullable=True),
    sa.Column('wind', sa.Float(), nullable=True),
    sa.Column('rain_mm', sa.Float(), nullable=True),
    sa.Column('direction_wind', sa.Float(), nullable=True),
    sa.Column('uv', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temperature_id'), 'temperature', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temperature_id'), table_name='temperature')
    op.drop_table('temperature')
    # ### end Alembic commands ###
